<?php
/**
 * Hand-crafted sample fixture for Customizer schema tests.
 *
 * The real fixture lives at all-configs.php and is regenerated by:
 *   wp eval-file tools/dump-customizer-configs.php
 *
 * This sample exists so the schema test suite can run on a fresh checkout
 * without WP-CLI access. It mirrors the row shape Customify_Customizer::get_config()
 * produces but only includes one row per type to keep the file small.
 */

return array(
    array(
        'name'    => 'sample_text',
        'type'    => 'text',
        'section' => 'general',
        'label'   => 'Sample text',
        'default' => '',
    ),
    array(
        'name'    => 'sample_select',
        'type'    => 'select',
        'section' => 'general',
        'label'   => 'Sample select',
        'default' => 'one',
        'choices' => array(
            'one' => 'One',
            'two' => 'Two',
        ),
    ),
    array(
        'name'      => 'sample_color',
        'type'      => 'color',
        'section'   => 'general_styling',
        'label'     => 'Sample color',
        'default'   => '#235787',
        'selector'  => '.cta a',
        'css_format' => 'color: {{value}};',
    ),
    array(
        'name'            => 'sample_slider',
        'type'            => 'slider',
        'section'         => 'general_layout',
        'label'           => 'Sample slider',
        'default'         => array('desktop' => array('unit' => 'px', 'value' => 20)),
        'device_settings' => true,
        'selector'        => '.row',
        'css_format'      => 'gap: {{value}};',
        'min'             => 0,
        'max'             => 100,
    ),
    array(
        'name'           => 'sample_checkbox',
        'type'           => 'checkbox',
        'section'        => 'general',
        'label'          => 'Sample checkbox',
        'checkbox_label' => 'Enable feature',
        'default'        => 0,
    ),
    array(
        'name'    => 'sample_dependent',
        'type'    => 'text',
        'section' => 'general',
        'label'   => 'Shown when select=one',
        'default' => '',
        'required' => array('sample_select', '=', 'one'),
    ),
    array(
        'name'    => 'sample_panel',
        'type'    => 'panel',
        'priority' => 100,
        'title'   => 'Sample panel',
    ),
    array(
        'name'    => 'sample_section',
        'type'    => 'section',
        'panel'   => 'sample_panel',
        'priority' => 10,
        'title'   => 'Sample section',
    ),
);
