<?php
/**
 * Block editor Page Settings panel.
 *
 * Registers post meta with REST API support and enqueues the React plugin
 * that renders the "Customify Page Settings" panel in the Document sidebar.
 * The classic-editor metabox (class-metabox.php) is used when the block editor
 * is disabled and reads/writes the same _customify_* meta keys.
 *
 * @since 0.4.14
 */
class Customify_Page_Settings {

	private static $_instance = null;

	public static function get_instance() {
		if ( is_null( self::$_instance ) ) {
			self::$_instance = new self();
		}
		return self::$_instance;
	}

	public function init() {
		add_action( 'init', array( $this, 'register_meta' ) );
		add_action( 'enqueue_block_editor_assets', array( $this, 'enqueue_assets' ) );
	}

	/**
	 * All _customify_* meta keys managed by this panel.
	 *
	 * @return string[]
	 */
	public function get_meta_keys() {
		return array(
			'content_layout',
			'sidebar',
			'page_header_display',
			'disable_header',
			'disable_header_top',
			'disable_header_main',
			'disable_header_bottom',
			'disable_page_title',
			'disable_content_vertical_padding',
			'disable_footer_top',
			'disable_footer_main',
			'disable_footer_bottom',
			'breadcrumb_display',
			'header_transparent_display',
		);
	}

	/**
	 * Register every meta key with show_in_rest so the block editor can read/write them.
	 */
	public function register_meta() {
		$post_types = function_exists( 'customify_get_meta_support_post_types' )
			? customify_get_meta_support_post_types()
			: get_post_types( array( 'public' => true ), 'names' );

		foreach ( $post_types as $post_type ) {
			foreach ( $this->get_meta_keys() as $key ) {
				register_post_meta(
					$post_type,
					'_customify_' . $key,
					array(
						'show_in_rest'      => true,
						'single'            => true,
						'type'              => 'string',
						'default'           => '',
						'sanitize_callback' => 'sanitize_text_field',
						'auth_callback'     => function() {
							return current_user_can( 'edit_posts' );
						},
					)
				);
			}
		}
	}

	/**
	 * Enqueue the block editor plugin script and pass config data.
	 *
	 * The asset.php file is generated by @wordpress/scripts and contains the
	 * exact dependency list and content hash for cache busting.
	 */
	public function enqueue_assets() {
		// `enqueue_block_editor_assets` fires in every block editor context:
		// post editor, widgets editor (WP 5.8+), site editor, customize
		// widgets. `PluginDocumentSettingPanel` only has a slot in the post
		// editor's Document sidebar, so loading this script anywhere else
		// is dead weight. It also pulls in `wp-editor` as a dependency
		// (via the `@wordpress/editor` import in src/), which trips WP's
		// "wp-editor script should not be enqueued together with the new
		// widgets editor" deprecation notice on the widgets screen.
		//
		// Screen base equals 'post' for the edit screen of every post type
		// (post, page, custom CPTs). Widgets editor uses base 'widgets';
		// site editor uses 'site-editor'. Skip everything that isn't a
		// post-edit screen.
		if ( function_exists( 'get_current_screen' ) ) {
			$screen = get_current_screen();
			if ( $screen && 'post' !== $screen->base ) {
				return;
			}
			// No-front-end utility CPTs (e.g. the Pro Hooks store) don't get the
			// Customify per-post settings panel — match the metabox gate.
			if (
				$screen && $screen->post_type
				&& function_exists( 'customify_get_meta_support_post_types' )
				&& ! in_array( $screen->post_type, customify_get_meta_support_post_types(), true )
			) {
				return;
			}
		}

		$asset_file = get_template_directory() . '/build/js/backend/page-settings.asset.php';

		if ( ! file_exists( $asset_file ) ) {
			return;
		}

		$asset = require $asset_file;

		wp_enqueue_script(
			'customify-page-settings',
			esc_url( get_template_directory_uri() ) . '/build/js/backend/page-settings.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		wp_enqueue_style(
			'customify-page-settings',
			esc_url( get_template_directory_uri() ) . '/build/css/backend/style-page-settings.css',
			array( 'wp-components' ),
			$asset['version']
		);

		$has_breadcrumb = class_exists( 'Customify_Breadcrumb' ) &&
		                  Customify_Breadcrumb::get_instance()->support_plugins_active();

		// Resolve the layout to use when the per-post sidebar meta is empty
		// (i.e. "Inherit from Customizer"). Computed server-side because the
		// JS panel doesn't have direct access to Customizer settings.
		$post      = get_post();
		$post_type = $post ? $post->post_type : '';
		if ( ! $post_type && function_exists( 'get_current_screen' ) ) {
			$screen    = get_current_screen();
			$post_type = $screen ? $screen->post_type : '';
		}
		$fallback_layout = $post_type && class_exists( 'Customify_Editor' )
			? Customify_Editor::customizer_sidebar_layout_for_post_type( $post_type )
			: 'content-sidebar';

		// Single-post user override: matches the frontend body.single-post rule
		// from inc/customizer/configs/single-blog-post.php — when editing a post,
		// the user's saved single_blog_post_content_width takes precedence over
		// the layout-derived size. Scoped to post_type === 'post' only; other
		// post types fall through to the layout map. Sent as the normalized
		// CSS length string (e.g., "600px") so JS doesn't have to recreate the
		// {value, unit} → length logic.
		$post_content_size = null;
		if ( 'post' === $post_type ) {
			$pcw = Customify()->get_setting( 'single_blog_post_content_width' );
			if ( is_array( $pcw ) && isset( $pcw['value'] ) && '' !== $pcw['value'] ) {
				$pcw_unit          = ! empty( $pcw['unit'] ) ? $pcw['unit'] : 'px';
				$post_content_size = $pcw['value'] . $pcw_unit;
			}
		}

		// wideSize for the editor's layout settings sync — pushed into
		// getSettings().__experimentalFeatures.layout so block dropdown labels
		// (e.g., "Wide width — Max 1200px wide") match the runtime CSS variable.
		//
		// Resolution mirrors what `--wp--style--global--wide-size` actually
		// resolves to in the editor iframe:
		//   - container_width has a saved value → editor.php's container_width
		//     branch emits `:root { --wp--style--global--wide-size: VALUE }`
		//     via the auto-CSS pipeline. wideSize === saved value.
		//   - container_width is unsaved → auto-CSS skips emission; only
		//     theme.json's static wideSize (1200px) applies. Read it via
		//     wp_get_global_settings() so any theme.json overrides upstream
		//     stay authoritative.
		$wide_size = null;
		$cw_raw    = get_theme_mod( 'container_width' );
		if ( is_array( $cw_raw ) && ! empty( $cw_raw['value'] ) ) {
			$wide_size = (int) $cw_raw['value'] . ( ! empty( $cw_raw['unit'] ) ? $cw_raw['unit'] : 'px' );
		} elseif ( is_numeric( $cw_raw ) && (int) $cw_raw > 0 ) {
			$wide_size = (int) $cw_raw . 'px';
		} else {
			$global_settings = function_exists( 'wp_get_global_settings' ) ? wp_get_global_settings() : array();
			$wide_size       = $global_settings['layout']['wideSize'] ?? '1200px';
		}

		// narrowWidth — used when content_layout meta is 'narrow'. Mirrors
		// customify_get_narrow_width_value() + the .site-content.content-narrow
		// frontend rule, so editor + frontend stay in sync.
		$narrow_width = function_exists( 'customify_get_narrow_width_value' )
			? customify_get_narrow_width_value()
			: '800px';

		wp_localize_script(
			'customify-page-settings',
			'customifyPageSettings',
			array(
				'sidebarLayouts'  => customify_get_config_sidebar_layouts(),
				'hasProFeatures'  => (bool) class_exists( 'Customify_Pro' ),
				'hasBreadcrumb'   => (bool) $has_breadcrumb,
				'fallbackLayout'  => $fallback_layout,
				'contentSizeMap'  => customify_get_layout_content_sizes(),
				'postType'        => $post_type,
				'postContentSize' => $post_content_size,
				'wideSize'        => $wide_size,
				'narrowWidth'     => $narrow_width,
			)
		);

		wp_set_script_translations( 'customify-page-settings', 'customify' );
	}
}

Customify_Page_Settings::get_instance()->init();
